DROP TABLE TB_ITEM_PEDIDO;
DROP TABLE TB_PRODUTO;
DROP TABLE TB_PEDIDO;
DROP TABLE TB_VENDEDOR;
DROP TABLE TB_CLIENTE;

------------------------
CREATE TABLE TB_VENDEDOR (
  CPF VARCHAR2(11), 
  NOME VARCHAR2(60), 
  ENDERECO VARCHAR2(60), 
  CIDADE VARCHAR2(30), 
  CEP VARCHAR2(8), 
  UF VARCHAR2(2), 
  DDD VARCHAR2(2), 
  TELEFONE VARCHAR2(9), 
  SALARIO_BASE NUMBER(7, 2), 
  TAXA_COMISSAO NUMBER(3, 1));
  
CREATE TABLE TB_CLIENTE (
  CPF VARCHAR2(11), 
  NOME VARCHAR2(60), 
  ENDERECO VARCHAR2(60), 
  CIDADE VARCHAR2(30), 
  CEP VARCHAR2(8), 
  UF VARCHAR2(2), 
  DDD VARCHAR2(2), 
  TELEFONE VARCHAR2(9), 
  LIMITE_CRED NUMBER(7, 2), 
  LIMITE_DISP NUMBER(7, 2));

CREATE TABLE TB_PEDIDO (
  NUMERO VARCHAR2(10), 
  SITUACAO NUMBER(1), 
  DATA_EMISSAO VARCHAR2(10), 
  DATA_PAGTO VARCHAR2(10), 
  FORMA_PAGTO NUMBER(1),
  CPF_CLIENTE VARCHAR2(11), 
  CPF_VENDEDOR VARCHAR2(11));

CREATE TABLE TB_ITEM_PEDIDO (
  SEQUENCIA NUMBER (5),
  QTDE_VENDIDA NUMBER(7, 2), 
  NUM_PEDIDO VARCHAR2 (10), 
  COD_PRODUTO VARCHAR2 (10));

CREATE TABLE TB_PRODUTO (
  CODIGO VARCHAR2(10), 
  DESCRICAO VARCHAR2(50), 
  QTDE_ESTOQUE NUMBER(7, 2), 
  PRECO NUMBER(7, 2), 
  ESTOQUE_MINIMO NUMBER(7, 2), 
  UNIDADE_MEDIDA VARCHAR2(2));
  
------------------------
ALTER TABLE TB_VENDEDOR
  ADD CONSTRAINT PK_VENDEDOR PRIMARY KEY (CPF);
  
ALTER TABLE TB_CLIENTE
  ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (CPF);
  
ALTER TABLE TB_PRODUTO
  ADD CONSTRAINT PK_PRODUTO PRIMARY KEY (CODIGO);
  
ALTER TABLE TB_PEDIDO
  ADD CONSTRAINT PK_PEDIDO PRIMARY KEY (NUMERO);
 
------------------------
ALTER TABLE TB_PEDIDO
  ADD CONSTRAINT FK_CLIENTE FOREIGN KEY(CPF_CLIENTE) REFERENCES TB_CLIENTE(CPF);

ALTER TABLE TB_PEDIDO
  ADD CONSTRAINT FK_VENDEDOR FOREIGN KEY(CPF_VENDEDOR) REFERENCES TB_VENDEDOR(CPF);
  
ALTER TABLE TB_ITEM_PEDIDO
  ADD CONSTRAINT FK_PEDIDO FOREIGN KEY(NUM_PEDIDO) REFERENCES TB_PEDIDO(NUMERO);
  
ALTER TABLE TB_ITEM_PEDIDO
  ADD CONSTRAINT FK_PRODUTO FOREIGN KEY(COD_PRODUTO) REFERENCES TB_PRODUTO(CODIGO);

ALTER TABLE TB_ITEM_PEDIDO
  ADD CONSTRAINT PK_ITEM_PEDIDO PRIMARY KEY (NUM_PEDIDO, COD_PRODUTO);